// variables
int LED1 = 3;
int LED2 = 4;
int LED3 = 5;
int LED4 = 6;
int LED5 = 7;
int LED6 = 8;
int DELAY_LED = 30;
int DELAY_RUN = 100;
int DELAY_ZIGZAG = 200;
int DELAY_LED1 = 300;

// functions
void setup()
{
  pinMode(LED1, OUTPUT);
  pinMode(LED2, OUTPUT);
  pinMode(LED3, OUTPUT);
  pinMode(LED4, OUTPUT);
  pinMode(LED5, OUTPUT);
  pinMode(LED6, OUTPUT);
}

void loop()
{
  digitalWrite(LED1, HIGH);
  delay(DELAY_LED);
  digitalWrite(LED2, HIGH);
  delay(DELAY_LED);
  digitalWrite(LED3, HIGH);
  delay(DELAY_LED);
  digitalWrite(LED4,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED5,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED6,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED5,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED4,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED3,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED2,HIGH);
  delay(DELAY_LED1);
  digitalWrite(LED1,LOW);
  delay(DELAY_LED);
  digitalWrite(LED2,LOW);
  delay(DELAY_LED);
  digitalWrite(LED3,LOW);
  delay(DELAY_LED);
  digitalWrite(LED4,LOW);
  delay(DELAY_LED);
  digitalWrite(LED5,LOW);
  delay(DELAY_LED);
  digitalWrite(LED6,LOW);
  delay(DELAY_LED);
  digitalWrite(LED5,LOW);
  delay(DELAY_LED);
  digitalWrite(LED4,LOW);
  delay(DELAY_LED);
  digitalWrite(LED3,LOW);
  delay(DELAY_LED);
  digitalWrite(LED2,LOW);
  delay(DELAY_LED1);
  digitalWrite(LED6, HIGH);
  delay(DELAY_LED);
  digitalWrite(LED5, HIGH);
  delay(DELAY_LED);
  digitalWrite(LED4, HIGH);
  delay(DELAY_LED);
  digitalWrite(LED3,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED2,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED1,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED2,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED3,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED4,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED5,HIGH);
  delay(DELAY_LED1);
  digitalWrite(LED6,LOW);
  delay(DELAY_LED);
  digitalWrite(LED5,LOW);
  delay(DELAY_LED);
  digitalWrite(LED4,LOW);
  delay(DELAY_LED);
  digitalWrite(LED3,LOW);
  delay(DELAY_LED);
  digitalWrite(LED2,LOW);
  delay(DELAY_LED);
  digitalWrite(LED1,LOW);
  delay(DELAY_LED);
  digitalWrite(LED2,LOW);
  delay(DELAY_LED);
  digitalWrite(LED3,LOW);
  delay(DELAY_LED);
  digitalWrite(LED4,LOW);
  delay(DELAY_LED);
  digitalWrite(LED5,LOW);
  delay(DELAY_LED1);
  digitalWrite(LED1, HIGH);
  delay(DELAY_LED);
  digitalWrite(LED2, HIGH);
  delay(DELAY_LED);
  digitalWrite(LED3, HIGH);
  delay(DELAY_LED);
  digitalWrite(LED4,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED5,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED6,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED5,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED4,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED3,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED2,HIGH);
  delay(DELAY_LED1);
  digitalWrite(LED1,LOW);
  delay(DELAY_LED);
  digitalWrite(LED2,LOW);
  delay(DELAY_LED);
  digitalWrite(LED3,LOW);
  delay(DELAY_LED);
  digitalWrite(LED4,LOW);
  delay(DELAY_LED);
  digitalWrite(LED5,LOW);
  delay(DELAY_LED);
  digitalWrite(LED6,LOW);
  delay(DELAY_LED);
  digitalWrite(LED5,LOW);
  delay(DELAY_LED);
  digitalWrite(LED4,LOW);
  delay(DELAY_LED);
  digitalWrite(LED3,LOW);
  delay(DELAY_LED);
  digitalWrite(LED2,LOW);
  delay(DELAY_LED1);
  digitalWrite(LED6, HIGH);
  delay(DELAY_LED);
  digitalWrite(LED5, HIGH);
  delay(DELAY_LED);
  digitalWrite(LED4, HIGH);
  delay(DELAY_LED);
  digitalWrite(LED3,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED2,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED1,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED2,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED3,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED4,HIGH);
  delay(DELAY_LED);
  digitalWrite(LED5,HIGH);
  delay(DELAY_LED1);
  digitalWrite(LED6,LOW);
  delay(DELAY_LED);
  digitalWrite(LED5,LOW);
  delay(DELAY_LED);
  digitalWrite(LED4,LOW);
  delay(DELAY_LED);
  digitalWrite(LED3,LOW);
  delay(DELAY_LED);
  digitalWrite(LED2,LOW);
  delay(DELAY_LED);
  digitalWrite(LED1,LOW);
  delay(DELAY_LED);
  digitalWrite(LED2,LOW);
  delay(DELAY_LED);
  digitalWrite(LED3,LOW);
  delay(DELAY_LED);
  digitalWrite(LED4,LOW);
  delay(DELAY_LED);
  digitalWrite(LED5,LOW);
  delay(DELAY_LED1);
  digitalWrite(LED1,HIGH);
  digitalWrite(LED2,HIGH);
  delay(DELAY_RUN);
  digitalWrite(LED1,LOW);
  digitalWrite(LED2,LOW);
  delay(DELAY_RUN);
  digitalWrite(LED3,HIGH);
  digitalWrite(LED4,HIGH);
  delay(DELAY_RUN);
  digitalWrite(LED3,LOW);
  digitalWrite(LED4,LOW);
  delay(DELAY_RUN);
  digitalWrite(LED5,HIGH);
  digitalWrite(LED6,HIGH);
  delay(DELAY_RUN);
  digitalWrite(LED5,LOW);
  digitalWrite(LED6,LOW);
  delay(DELAY_RUN);
  digitalWrite(LED4,HIGH);
  digitalWrite(LED3,HIGH);
  delay(DELAY_RUN);
  digitalWrite(LED4,LOW);
  digitalWrite(LED3,LOW);
  delay(DELAY_RUN);
  digitalWrite(LED2,HIGH);
  digitalWrite(LED1,HIGH);
  delay(DELAY_RUN);
  digitalWrite(LED2,LOW);
  digitalWrite(LED1,LOW);
  delay(DELAY_LED1);
  digitalWrite(LED1,HIGH);
  digitalWrite(LED6,HIGH);  
  delay(DELAY_RUN);
  digitalWrite(LED1,LOW);
  digitalWrite(LED6,LOW);
  delay(DELAY_RUN); 
  digitalWrite(LED2,HIGH);
  digitalWrite(LED5,HIGH);  
  delay(DELAY_RUN);
  digitalWrite(LED2,LOW);
  digitalWrite(LED5,LOW);
  delay(DELAY_RUN);
  digitalWrite(LED3,HIGH);
  digitalWrite(LED4,HIGH);  
  delay(DELAY_RUN);
  digitalWrite(LED3,LOW);
  digitalWrite(LED4,LOW);
  delay(DELAY_RUN);
  digitalWrite(LED2,HIGH);
  digitalWrite(LED5,HIGH);  
  delay(DELAY_RUN);
  digitalWrite(LED2,LOW);
  digitalWrite(LED5,LOW);
  delay(DELAY_RUN);
  digitalWrite(LED1,HIGH);
  digitalWrite(LED6,HIGH);  
  delay(DELAY_RUN);
  digitalWrite(LED1,LOW);
  digitalWrite(LED6,LOW);
  delay(DELAY_RUN);
    digitalWrite(LED1,HIGH);
  digitalWrite(LED6,HIGH);  
  delay(DELAY_RUN);
  digitalWrite(LED1,LOW);
  digitalWrite(LED6,LOW);
  delay(DELAY_RUN);
  digitalWrite(LED2,HIGH);
  digitalWrite(LED5,HIGH);  
  delay(DELAY_RUN);
  digitalWrite(LED2,LOW);
  digitalWrite(LED5,LOW);
  delay(DELAY_RUN);
  digitalWrite(LED3,HIGH);
  digitalWrite(LED4,HIGH);  
  delay(DELAY_RUN);
  digitalWrite(LED3,LOW);
  digitalWrite(LED4,LOW);
  delay(DELAY_RUN);
  digitalWrite(LED2,HIGH);
  digitalWrite(LED5,HIGH);  
  delay(DELAY_RUN);
  digitalWrite(LED2,LOW);
  digitalWrite(LED5,LOW);
  delay(DELAY_RUN);
  digitalWrite(LED1,HIGH);
  digitalWrite(LED6,HIGH);  
  delay(DELAY_RUN);
  digitalWrite(LED1,LOW);
  digitalWrite(LED6,LOW);
  delay(DELAY_LED1);
  digitalWrite(LED1,HIGH);
  digitalWrite(LED3,HIGH);
  delay(DELAY_ZIGZAG);
  digitalWrite(LED1,LOW);
  digitalWrite(LED3,LOW);
  delay(DELAY_ZIGZAG);
  digitalWrite(LED4,HIGH);
  digitalWrite(LED6,HIGH);
  delay(DELAY_ZIGZAG);
  digitalWrite(LED4,LOW);
  digitalWrite(LED6,LOW);
  delay(DELAY_ZIGZAG);
  digitalWrite(LED2,HIGH);
  digitalWrite(LED5,HIGH);
  delay(DELAY_ZIGZAG);
  digitalWrite(LED2,LOW);
  digitalWrite(LED5,LOW);
  delay(DELAY_ZIGZAG);
  digitalWrite(LED1,HIGH);
  digitalWrite(LED3,HIGH);
  digitalWrite(LED4,HIGH);
  digitalWrite(LED6,HIGH);
  delay(DELAY_LED1);
}
